const cardImages = [
    {
        type: 'android',
        
        "src": "/images/android.png", matched: false },
    { "src": "/images/angular.png", matched: false },
  { "src": "/images/css.png", matched: false },
  { "src": "/images/docker.png", matched: false },
  { "src": "/images/drupal.png", matched: false }, 
  { "src": "/images/git.png", matched: false },
   { "src": "/images/c#.png",matched: false  },
    { "src": "/images/github.png", matched: false  },
    { "src": "/images/go.png", matched: false  },
    { "src": "/images/heroku.png", matched: false  },
    { "src": "/images/html.png",matched: false  },
    { "src": "/images/java.png", matched: false  },
    { "src": "/images/javascript.png", matched: false  },
    { "src": "/images/linux.png", matched: false  },
    { "src": "/images/mocha.png", matched: false  },
    { "src": "/images/mongo.png", matched: false  },
    { "src": "/images/msteams.png", matched: false  },
    { "src": "/images/mysql.png", matched: false  },
    { "src": "/images/node.png", matched: false  },
    { "src": "/images/paragon.png", matched: false  },
    { "src": "/images/postgresql.png", matched: false  },
    { "src": "/images/postman.png", matched: false  },
    { "src": "/images/python.png", matched: false  },
    { "src": "/images/rail.png", matched: false  },
    { "src": "/images/react.png", matched: false  },
    { "src": "/images/scala.png", matched: false  },
    { "src": "/images/slack.png", matched: false  },
    { "src": "/images/swift.png", matched: false  },
    { "src": "/images/typescript.png", matched: false  },
    { "src": "/images/unity.png", matched: false  },
    { "src": "/images/visualstudio.png", matched: false  },
    { "src": "/images/vue.png", matched: false  },
  ];